### ISSUE TITLE
speak on/off issues

### ISSUE THREAD

**Issue by ginolee218** [UBIQCONN/uti-imx_device_fsl#4]
1. Can't get current speaker on/off status use android api
2. Can't turn on speaker use android api

====================================   Log for speaker on  ===============================

15:02:08.945   338-1731  audio_hw_primary                    pid-338                         I  **select_output_device(), headphone 0 ,headset 0 ,speaker 2**
15:02:08.945   338-1731  audio_hw_primary                    pid-338                         D  start_output_stream: pcm_open: card: 0, pcm_device_id: 0, rate: 48000, channel: 2, format: 0, period_size: 0xc0, flag: 9
15:02:08.946   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() device->mix: 4 -> 30
15:02:08.948   338-1731  audio_hw_primary                    pid-338                         I  out_write: first frame write, out stream 0xea802950
15:02:08.948   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() set input(30) device to 4, patch_handle 3
15:02:08.953   338-1852  audio_hw_primary                    pid-338                         W  start_input_stream...., mode 0, in->device 0x4
15:02:09.019   338-1852  audio_hw_primary                    pid-338                         W  card 0, port 0 device 0x4
15:02:09.019   338-1852  audio_hw_primary                    pid-338                         W  rate 48000, channel 2 format 0, period_size 0x100
15:03:00.726   338-393   audio_hw_primary                    pid-338                         I  adev_set_mode mode 3
15:03:00.726   338-393   audio_hw_primary                    pid-338                         W  Leaving IN_CALL state, in_call=0, mode=3
15:03:00.775   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() mix->device: 13 -> 2
15:03:00.835   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() mix->device: 13 -> 2
15:03:00.995   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() mix->device: 13 -> 2

====================================   Log for speaker off  ===============================

15:03:11.481   338-393   audio_hw_primary                    pid-338                         I  adev_set_mode mode 2
15:03:11.481   338-393   audio_hw_primary                    pid-338                         W  Entering IN_CALL state, in_call=0
15:03:11.481   338-393   audio_hw_primary                    pid-338                         I  **select_output_device(), headphone 0 ,headset 0 ,speaker 0**
15:03:11.535   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() mix->device: 13 -> 2
15:03:11.695   338-393   audio_hw_primary                    pid-338                         D  adev_create_audio_patch() mix->device: 13 -> 2

**Comment by UBIQCONN** [comment]
Review solution https://github.com/UBIQCONN/uti-imx_device_fsl/pull/26
